// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfwQgeRvkFgk0H2-d2DxNzIJTCiXKIFA',
    appId: '1:190856544684:web:c870106f2d77b41393fa09',
    messagingSenderId: '190856544684',
    projectId: 'diaryv-3733d',
    authDomain: 'diaryv-3733d.firebaseapp.com',
    storageBucket: 'diaryv-3733d.appspot.com',
    measurementId: 'G-E4JWRKNMQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl49Uni_WPnh0IYu-UCiYspinQQ7fhZvU',
    appId: '1:190856544684:android:71de097f30e5fafe93fa09',
    messagingSenderId: '190856544684',
    projectId: 'diaryv-3733d',
    storageBucket: 'diaryv-3733d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfv4V3VGbM2VOFqb2oSh3xCwUNClvCucM',
    appId: '1:190856544684:ios:ace181b8f3d1f0c193fa09',
    messagingSenderId: '190856544684',
    projectId: 'diaryv-3733d',
    storageBucket: 'diaryv-3733d.appspot.com',
    iosBundleId: 'com.example.videoDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfv4V3VGbM2VOFqb2oSh3xCwUNClvCucM',
    appId: '1:190856544684:ios:e7c550771135811b93fa09',
    messagingSenderId: '190856544684',
    projectId: 'diaryv-3733d',
    storageBucket: 'diaryv-3733d.appspot.com',
    iosBundleId: 'com.example.videoDiary.RunnerTests',
  );
}
